buy/urls.py
from django.urls import path

from buy.views import BuyItemView, BuyOrderView, CancelView, SuccessView

urlpatterns = [
    path(
        "order/<int:order_id>/",
        BuyOrderView.as_view(),
        name="buy-order",
    ),
    path(
        "<int:item_id>/",
        BuyItemView.as_view(),
        name="buy-item",
    ),
    path("cancel/", CancelView.as_view(), name="cancel"),
    path("success/", SuccessView.as_view(), name="success"),
]

item/urls.py
from django.urls import path

from item.views import ItemView

urlpatterns = [
    path("<int:id>/", ItemView.as_view(), name="item"),
]

order/urls.py
from django.urls import path

from order.views import OrderView

urlpatterns = [
    path("<int:id>/", OrderView.as_view(), name="order"),
]

testProject4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("item/", include("item.urls")),
    path("buy/", include("buy.urls")),
    path("order/", include("order.urls")),
]

item/models.py
from django.db import models


class Item(models.Model):
    """Модель товара"""

    name = models.CharField(max_length=255, unique=True, verbose_name="название")
    description = models.TextField(verbose_name="описание")
    price = models.DecimalField(max_digits=20, decimal_places=2, verbose_name="цена")

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return f"Item({self.name}, {self.description}, {self.price})"

order/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from buy.services.stripe import (
    save_or_update_stripe_discount,
    save_or_update_stripe_tax_rate,
)
from item.models import Item


class Order(models.Model):
    """Модель заказа объединяющая Items"""

    name = models.CharField(max_length=255, verbose_name="название")
    items = models.ManyToManyField(Item, through="OrderItemM2M")

    discount = models.ForeignKey(
        "Discount",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="order",
        verbose_name="скидка",
    )
    tax = models.ForeignKey(
        "Tax",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="order",
        verbose_name="налог",
    )

    class Meta:
        verbose_name = "заказ"
        verbose_name_plural = "заказы"

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return f"Order({self.name})"


class OrderItemM2M(models.Model):
    """Модель для связи Item и Order для хранения товаров заказа и их количества"""

    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="заказ")
    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name="товар")
    count = models.PositiveIntegerField(
        verbose_name="количество",
        validators=[MinValueValidator(1)],
    )

    class Meta:
        verbose_name = "товар заказа"
        verbose_name_plural = "товары заказа"
        unique_together = ("order", "item")

    def __str__(self) -> str:
        return f"Заказ: {self.order}, товар: {self.item}"


class Discount(models.Model):
    """Модель скидки для заказа"""

    name = models.CharField(max_length=255, verbose_name="название")
    percentage = models.PositiveIntegerField(
        verbose_name="процент скидки",
        validators=[MinValueValidator(1), MaxValueValidator(100)],
    )
    stripe_id = models.CharField(
        max_length=255, blank=True, unique=True, null=True, verbose_name="stripe_id"
    )

    def save(self, *args, **kwargs):
        self.stripe_id = save_or_update_stripe_discount(
            self.stripe_id, self.name, self.percentage
        )
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "скидка"
        verbose_name_plural = "скидки"

    def __str__(self) -> str:
        return self.name


class Tax(models.Model):
    """Модель налога для заказа"""

    name = models.CharField(max_length=255, verbose_name="название")
    percentage = models.PositiveIntegerField(
        verbose_name="процент налога",
        validators=[MinValueValidator(1), MaxValueValidator(100)],
    )
    stripe_id = models.CharField(
        max_length=255, blank=True, null=True, unique=True, verbose_name="stripe_id"
    )

    def save(self, *args, **kwargs):
        self.stripe_id = save_or_update_stripe_tax_rate(
            self.stripe_id, self.name, self.percentage
        )
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "налог"
        verbose_name_plural = "налоги"

    def __str__(self) -> str:
        return self.name

buy/views.py
from typing import Any

from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views import View
from django.views.generic import TemplateView

from buy.services.stripe import (
    create_stripe_item_payment_session,
    create_stripe_order_payment_session,
)
from item.models import Item
from order.models import Order


class BuyItemView(View):
    """View для получения stripe checkout_session_id, необходимого для оплаты Item"""

    def get(self, request, *args, item_id: int, **kwargs) -> JsonResponse:
        item = get_object_or_404(Item, id=item_id)

        checkout_session_id = create_stripe_item_payment_session(
            item.id, item.name, item.price
        )
        return JsonResponse({"id": checkout_session_id})


class BuyOrderView(View):
    """View для получения stripe checkout_session_id, необходимого для оплаты Order"""

    def get(self, request, *args, order_id: int, **kwargs) -> JsonResponse:
        query_set = Order.objects.prefetch_related("items").select_related(
            "discount", "tax"
        )
        order = get_object_or_404(query_set, id=order_id)

        checkout_session_id = create_stripe_order_payment_session(order)
        return JsonResponse({"id": checkout_session_id})


class SuccessView(TemplateView):
    """View для отображения страницы об успешной оплате"""

    template_name = "buy/success.html"

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(id=id, **kwargs)
        context["title"] = "Удачная покупка"
        return context


class CancelView(TemplateView):
    """View для отображения страницы об неуспешной оплате"""

    template_name = "buy/cancel.html"

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(id=id, **kwargs)
        context["title"] = "Неудачная покупка"
        return context

item/views.py
from typing import Any

from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from django.conf import settings

from item.models import Item


class ItemView(TemplateView):
    """View для отображения информации о товаре"""

    template_name = "item/item.html"

    def get_context_data(self, id: int, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(id=id, **kwargs)

        item = get_object_or_404(Item, id=id)
        context["title"] = item.name
        context["item"] = item
        context["STRIPE_PUBLIC_KEY"] = settings.STRIPE_PUBLIC_KEY
        return context

order/views.py
from typing import Any

from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from django.conf import settings

from order.models import Order


class OrderView(TemplateView):
    """View для отображения информации о заказе"""

    template_name = "order/order.html"

    def get_context_data(self, id: int, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(id=id, **kwargs)

        order = get_object_or_404(Order.objects.prefetch_related("items"), id=id)
        context["title"] = order.name
        context["order"] = order
        context["STRIPE_PUBLIC_KEY"] = settings.STRIPE_PUBLIC_KEY
        return context

buy/templates/buy/cancel.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'styles/cancel.css'%}" type="text/css">

    <div class="error-message">
        <h1>Оплата не прошла!</h1>
        <p>К сожалению, произошла ошибка при обработке вашего платежа. Пожалуйста, попробуйте еще раз.</p>
        <a href="/">Вернуться на главную страницу</a>
    </div>
{% endblock %}

buy/templates/buy/success.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'styles/success.css'%}" type="text/css">

    <div class="success-message">
        <h1>Оплата прошла успешно!</h1>
        <p>Спасибо за вашу покупку. Ваш заказ будет обработан в ближайшее время.</p>
        <a href="/">Вернуться на главную страницу</a>
    </div>
{% endblock %}

item/templates/item/item.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'styles/item.css'%}" type="text/css">
    <script src="https://js.stripe.com/v3/"></script>

    <div class="container">
        <h1>Название товара: {{ item.name }}</h1>
        <p>Описание: {{ item.description }}</p>
        <p class="price">Цена: {{ item.price }} руб.</p>
        <button type="button" id="checkout-button">Купить</button>
    </div>

    <script>
        const stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
        const checkoutButton = document.getElementById("checkout-button");

        checkoutButton.addEventListener("click", () => {
            fetch("{% url 'buy-item' item.id %}")
                .then(result => result.json())
                .then(session => stripe.redirectToCheckout({ sessionId: session.id }))
                .then(result => {
                    if (result.error) {
                        alert(result.error.message);
                    }
                })
                .catch(error => {
                  console.error("Error:", error);
                });
        });
    </script>
{% endblock %}

order/templates/order/order.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'styles/order.css' %}" type="text/css">
    <script src="https://js.stripe.com/v3/"></script>

    <div class="container">
        <h1>Заказ: {{ title }}</h1>
        <div id="products">
            {% for order_item_m2m in order.orderitemm2m_set.all %}
                <div class="product">
                    <h2>{{ order_item_m2m.item.name }}</h2>
                    <p>Описание: {{ order_item_m2m.item.description }}</p>
                    <p class="price">Цена: {{ order_item_m2m.item.price }} руб.</p>
                    <span class="quantity-label">Количество: <span id="quantity">{{ order_item_m2m.count }}</span></span>
                </div>
            {% endfor %}
        </div>

        <div class="summary">
            <p class="discount">Скидка: {{ order.discount.name }} {{ order.discount.percentage }} %</p>
            <p class="tax">Налог: {{ order.tax.name }} {{ order.tax.percentage }} %</p>
        </div>

        <button type="button" id="checkout-button">Купить все</button>
    </div>

    <script>
        const stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
        const checkoutButton = document.getElementById("checkout-button");

        checkoutButton.addEventListener("click", () => {
            fetch("{% url 'buy-order' order.id %}")
                .then(result => result.json())
                .then(session => stripe.redirectToCheckout({ sessionId: session.id }))
                .then(result => {
                    if (result.error) {
                        alert(result.error.message);
                    }
                })
                .catch(error => {
                    console.error("Error:", error);
                });
        });
    </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>